### ISSUE TITLE
vim: modeline not considered anymore

### ISSUE THREAD

**Issue by LeSpocky** [grml/grml-etc-core#154]
After upgrading my setup from v0.16.0 to v0.19.6 Vim does not evaluate modelines anymore.  I have lines from Kconfig or Make files like those:

```
# vim: ft=kconfig noet tw=72 ts=8 sw=8
```

or 

```
# vim: ft=make noet tw=72 ts=8 sw=8
```

When switching back and forth between the above mentioned versions of grml-etc-core the Vim 8.2 of my venerable Debian GNU/Linux 11 (bullseye) considers the modeline when starting Vim or not.  Manually entering those things in Vim with `:set …` works as expected.

I have some things in `~/.vimrc.local` but I can not see if they are related.  (It's public [here](https://github.com/LeSpocky/dotfiles/blob/main/vim/.vimrc.local).)

I'm using the grml vimrc like this: I have a symlink `~/.vimrc` to *grml-etc-core/etc/vim/vimrc* …

Maybe related to #92 which was a major rework?

**Comment by mika** [comment]
@LeSpocky does https://stackoverflow.com/questions/4590191/why-does-vim-ignore-my-modeline-values help in tracking this down? I recall that `/usr/share/vim/vimXX/debian.vim` defines `set nomodline` (for security reasons). In 31dc671f573000a4e83b715c2f1e52829d604e1c we indeed had some changes to the way we use the Debian configuration, so that might *very* well be related, though I don't have any idea yet how to improve that.

**Comment by LeSpocky** [comment]
Bingo! 

I just tried `:set modeline?` on both versions and the new one has *nomodeline* while the old one has not.
So I just added this to my *~/.vimrc.local* and it works:

```
set modeline
```

Thanks for the quick support.

**Comment by mika** [comment]
As discussed on IRC, the default is coming from Debian and for security reasons it might make sense to leave it at that by default, one can easily enable `set modeline` in `~/.vimrc.local` if needed, and now we have an archived issue hereby, so closing as agreed.

Thanks for mentioning https://editorconfig.org/ on IRC, BTW - TIL! :)
