### ISSUE TITLE
"Ctrl e" is slow

### ISSUE THREAD

**Issue by mssdvd** [grml/grml-etc-core#62]
When I press "Ctrl e", there is a delay before positioning on the last character.
"Ctrl a" works normally.

grml-zsh-config 0.14.2 from Arch.

**Comment by KellerFuchs** [comment]
I can reproduce the issue.

**Comment by ft** [comment]
Yes, that's because of the binding of `insert-datestamp`, which is bound to

```
bind2maps emacs viins       -- -s '^ed' insert-datestamp
```

The shells waits for a timeout to figure out if the user wanted the `Ctrl-e` binding, or
or if there's a `d` coming to complete the `Ctrl-e d` binding.

I bet, that should have been `'\ed'` instead. @mika? That way, `ESC d` (which in many
would terminals gets emitted by 'Alt-d') trigger that widget.

**Comment by mssdvd** [comment]
@ft Thank you!

**Comment by ft** [comment]
Fixed in f98b0469485

**Comment by mika** [comment]
Reopening as per https://twitter.com/gregoa_/status/889627954313121792 -> "Alt-d for dates is not a good idea, as that's readline's default for kill-word (delete word to the right) (grml's zshrc, f98b046)"

@ft any suggestion how to handle this now? :)

**Comment by ft** [comment]
Right. Open to suggestions. I don't have a preference.

**Comment by ft** [comment]
So, since nobody made a better suggestion, I am moving this to `C-x d` which has no previous binding in our setup and we're using the `C-x …` prefix for a couple of other things, as well.

Fixed (again) in 65ac134.
